Areas/Admin/Controllers/InstructorsController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.ViewModel.InstructorVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = PolicyConstants.AdminPolicy)]
    public class InstructorsController : Controller
    {
        private readonly IInstructorService _instructorService;
        private const string _instructorsPartialConstant = "InstructorsPartial";

        public InstructorsController(IInstructorService instructorService)
        {
            _instructorService = instructorService;
        }

        [HttpPost]
        public async Task<IActionResult> InstructorsPartial(string? searchFilter, string? statusFilter)
        {
            var pagination = await _instructorService.GetInstructorsPartialAsync(searchFilter, statusFilter);

            if (pagination.Items?.ToList().Count == 0)
            {
                ViewBag.Message = "Nothing Found";
            }

            return PartialView(viewName: _instructorsPartialConstant, pagination);
        }

        public async Task<IActionResult> Index()
        {
            var pagination = await _instructorService.GetInstructorsPartialAsync();

            if (pagination.Items?.ToList().Count == 0)
            {
                ViewBag.Message = "Nothing Found";
            }

            return View(pagination);
        }

        [HttpPost]
        public async Task<IActionResult> ApproveInstructor(Guid id)
        {
            bool result = await _instructorService.ApproveAsync(id);

            return new JsonResult(new { success = result });
        }

        [HttpPost]
        public async Task<IActionResult> BanInstructor(Guid id)
        {
            bool result = await _instructorService.BanAsync(id);
            return new JsonResult(new { success = result });
        }

        [HttpPost]
        public async Task<IActionResult> UnBanInstructor(Guid id)
        {
            bool result = await _instructorService.UnbanAsync(id);
            return new JsonResult(new { success = result });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteInstructor(Guid id)
            => new JsonResult(new { success = await _instructorService.DeleteAsync(id) });

        public async Task<IActionResult> Profile(Guid id)
        {
            InstructorAccountVm instructorAccountVm = await _instructorService.GetProfileDataAsync(id);
            return View(instructorAccountVm);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(InstructorAccountVm instructorAccountVm)
        {
            bool result = await _instructorService.UpdateProfileAsync(instructorAccountVm);

            if (!result)
                return View(instructorAccountVm);

            TempData["ProfileUpdated"] = true;
            return Redirect($"/Admin/Instructors/Profile/{instructorAccountVm.Id}");
        }

        [HttpPost]
        public async Task<IActionResult> UploadProfileImage([FromRoute] Guid id, [FromForm] IFormFile file)
        {
            bool result = await _instructorService.UploadProfileImageAsync(id, file);
            return new JsonResult(new { success = result });
        }

        [HttpPut]
        public async Task<IActionResult> ChangeProfileImage(Guid id, IFormFile file)
        {
            bool result = await _instructorService.ChangeProfileImageAsync(id, file);
            return new JsonResult(new { success = result });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteProfileImage(Guid id)
        {
            bool result = await _instructorService.DeleteProfileImageAsync(id);
            return new JsonResult(new { success = result });
        }

        [HttpPost]
        public async Task<JsonResult> SendConfirmationMail(Guid id)
            => new JsonResult(new { success = await _instructorService.SendConfirmationMailAsync(id) });

        [HttpPost]
        public async Task<JsonResult> SendPasswordGenerateMail(Guid id)
            => new JsonResult(new { success = await _instructorService.SendPasswordGenerateMailAsync(id) });

        [HttpPut]
        public async Task<JsonResult> ChangeShowcase(Guid id)
        {
            (bool success, string message) = await _instructorService.ChangeInstructorShowcaseAsync(id);
            return new JsonResult(new {
                success = success,
                message = message
            });
        }

    }
}

Areas/Auth/Controllers/InstructorController.cs
using CodinaxProjectMvc.Business.Abstract.InfrastructureServices;
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.DataAccess.Models.Identity;
using CodinaxProjectMvc.DataList;
using CodinaxProjectMvc.ViewModel.InstructorVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CodinaxProjectMvc.Areas.Auth.Controllers
{
    [Area("Auth")]
    [Authorize(Policy = PolicyConstants.NotAuthRequiredPolicy)]
    public class InstructorController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IAuthService _authService;

        public InstructorController(UserManager<AppUser> userManager, IAuthService authService)
        {
            _userManager = userManager;
            _authService = authService;
        }

        public IActionResult Apply()
        {
            ViewBag.Countries = new SelectList(Countries.All, nameof(Country.Name), nameof(Country.Name));
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Apply(InstructorApplyVm instructorApplyVm)
        {
            bool result = await _authService.InstructorApplyAsync(instructorApplyVm);
                
            if (!result)
            {
                ViewBag.Countries = new SelectList(Countries.All, nameof(Country.Name), nameof(Country.Name));
                return View(instructorApplyVm);
            }

            TempData["InstructorApplySuccess"] = true;
            return Redirect("/Home/Index");
        }
    }
}

Areas/Instructor/Controllers/AccountController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Business.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.ViewModel.InstructorVm;
using CodinaxProjectMvc.ViewModel.StudentVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorize(Policy = PolicyConstants.InstructorPolicy)]
    public class AccountController : Controller
    {
        private readonly IInstructorService _instructorService;

        public AccountController(IInstructorService instructorService)
        {
            _instructorService = instructorService;
        }

        public async Task<IActionResult> Profile()
        {
            InstructorAccountVm instructorAccountVm = await _instructorService.GetProfileDataAsync();
            return View(instructorAccountVm);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(InstructorAccountVm instructorAccountVm)
        {
            bool result = await _instructorService.UpdateProfileAsync(instructorAccountVm);

            if (!result)
                return View(instructorAccountVm);

            TempData["ProfileUpdated"] = true;
            return Redirect($"/Instructor/Account/Profile");
        }

        [HttpPost]
        public async Task<IActionResult> UploadProfileImage([FromRoute] Guid id, [FromForm] IFormFile file)
        {
            bool result = await _instructorService.UploadProfileImageAsync(id, file);
            return new JsonResult(new { success = result });
        }

        [HttpPut]
        public async Task<IActionResult> ChangeProfileImage(Guid id, IFormFile file)
        {
            bool result = await _instructorService.ChangeProfileImageAsync(id, file);
            return new JsonResult(new { success = result });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteProfileImage(Guid id)
        {
            bool result = await _instructorService.DeleteProfileImageAsync(id);
            return new JsonResult(new { success = result });
        }

        [HttpPost]

        public async Task<IActionResult> ChangePassword(InstructorResetPasswordVm instructorResetPasswordVm)
        {
            bool result = await _instructorService.ChangePasswordAsync(instructorResetPasswordVm);
            var instructorAccountVm = await _instructorService.GetProfileDataAsync();

            if (!result)
            {
                instructorAccountVm.Password = instructorResetPasswordVm.Password;
                instructorAccountVm.ConfirmPassword = instructorResetPasswordVm.ConfirmPassword;
                return View(viewName: nameof(Profile), instructorAccountVm);
            }

            TempData["PasswordUpdated"] = true;
            return View(viewName: nameof(Profile), instructorAccountVm);
        }

    }
}

Areas/Instructor/Controllers/CoursesController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorize(Policy = PolicyConstants.InstructorPolicy)]
    public class CoursesController : Controller
    {
        private readonly IInstructorService _instructorService;

        public CoursesController(IInstructorService instructorService)
        {
            _instructorService = instructorService;
        }

        public async Task<IActionResult> Index()
            => View(await _instructorService.GetInstructorCoursesAsync(HttpContext.User.Identity.Name));

        public async Task<IActionResult> Single(Guid id)
            => View(await _instructorService.GetInstructorCourseSingleAsync(HttpContext.User.Identity.Name, id));
    }
}

Areas/Instructor/Controllers/EventsController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.Filters;
using CodinaxProjectMvc.ViewModel.EventVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorize(Policy = PolicyConstants.InstructorPolicy)]
    public class EventsController : Controller
    {
        private readonly IEventService _eventService;

        public EventsController(IEventService eventService)
        {
            _eventService = eventService;
        }

        [EventViewFilterFactory]
        public IActionResult Index()
            => View();

        [HttpGet]
        public async Task<JsonResult> ListEvents()
            => Json(await _eventService.ListEventsAsync());

        [HttpPost]
        public async Task<JsonResult> AddOrUpdateEvent(EventActionVm eventActionVm)
            => Json(new { success = await _eventService.EventAddOrUpdateAsync(eventActionVm) });

        [HttpDelete]
        public async Task<JsonResult> DeleteEvent(Guid id)
            => Json(new { success = await _eventService.DeleteEventAsync(id) });

    }
}

Areas/Instructor/Controllers/LecturesController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.DataAccess.Models;
using CodinaxProjectMvc.ViewModel.FeatureVm;
using CodinaxProjectMvc.ViewModel.LectureVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorize(Policy = PolicyConstants.InstructorPolicy)]
    public class LecturesController : Controller
    {
        private readonly ILectureService _lectureService;

        public LecturesController(ILectureService lectureService)
        {
            _lectureService = lectureService;
        }

        public IActionResult Create(Guid id)
            => View(new LectureCreateVm(id));

        [HttpPost]
        public async Task<IActionResult> Create(LectureCreateVm lectureCreateVm)
        {
            bool result = await _lectureService.CreateLectureAsync(lectureCreateVm);
            if (!result)
                return View(lectureCreateVm);
            TempData["LectureCreatedSuccess"] = true;
            return Redirect($"/Instructor/Modules/Index/{lectureCreateVm.ModuleId}");
        }

        public async Task<IActionResult> Update(Guid id)
            => View(await _lectureService.GetLectureUpdateDataAsync(id));

        [HttpPost]
        public async Task<IActionResult> Update(LectureUpdateVm lectureUpdateVm)
        {
            bool result = await _lectureService.UpdateLecturesAsync(lectureUpdateVm);
            if (!result)
                return View(lectureUpdateVm);
            TempData["LectureUpdatedSuccess"] = true;
            return View(lectureUpdateVm);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(Guid id)
            => new JsonResult(new { success = await _lectureService.DeleteLectureAsync(id) });

        [HttpGet("Instructor/[controller]/{action}/{moduleId}/{lectureId}")]
        public IActionResult AddFile(Guid moduleId, Guid lectureId)
            => View(new LectureFileCreateVm(moduleId, lectureId));

        [HttpPost]
        public async Task<IActionResult> AddFile(LectureFileCreateVm lectureFileCreateVm)
        {
            bool result = await _lectureService.AddLectureFileAsync(lectureFileCreateVm);
            if (!result)
                return View(lectureFileCreateVm);

            TempData["LectureFileCreatedSuccess"] = true;
            return Redirect($"/Instructor/Modules/Index/{lectureFileCreateVm.ModuleId}");
        }

        public async Task<IActionResult> UpdateFile(Guid id)
            => View(await _lectureService.GetLectureFileUpdateDataAsync(id));


        [HttpPost]
        public async Task<IActionResult> UpdateFile(LectureFileUpdateVm lectureFileUpdateVm)
        {
            bool result = await _lectureService.UpdateLectureFileAsync(lectureFileUpdateVm);
            if (!result)
                return View(lectureFileUpdateVm);
            TempData["LectureFileUpdatedSuccess"] = true;
            return View(lectureFileUpdateVm);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteFile(Guid id)
            => new JsonResult(new { success = await _lectureService.DeleteLectureFileAsync(id) });

    }
}

Areas/Instructor/Controllers/SearchController.cs
using CodinaxProjectMvc.Business.Abstract.PersistenceServices;
using CodinaxProjectMvc.Constants;
using CodinaxProjectMvc.DataAccess.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorize(Policy = PolicyConstants.InstructorPolicy)]
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;

        public SearchController(ISearchService searchService)
        {
            _searchService = searchService;
        }

        public async Task<IActionResult> Index(string content)
            => PartialView(viewName: "SearchPartial", await _searchService.SearchAsync(content));

        public IActionResult SearchByCourse(string content)
            => View(_searchService.Search<Course>(content));

        public IActionResult SearchByModule(string content)
            => View(_searchService.Search<Module>(content));

        public IActionResult SearchByLecture(string content)
            => View(_searchService.Search<Lecture>(content));

        public IActionResult SearchByContent(string content)
            => View(_searchService.Search<LectureFile>(content));
    }
}

ViewComponents/FaqViewComponents/FaqViewComponent.cs
using CodinaxProjectMvc.DataAccess.Abstract.Repositories;
using CodinaxProjectMvc.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodinaxProjectMvc.ViewComponents.FaqViewComponents
{
    public class FaqViewComponent : ViewComponent
    {
        private readonly IReadRepository<Faq> _faqReadRepository;

        public FaqViewComponent(IReadRepository<Faq> faqReadRepository)
        {
            _faqReadRepository = faqReadRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        => View(await _faqReadRepository.GetWhere(x => !x.IsDeleted && !x.IsArchived)
               .ToListAsync());
        
    }
}

ViewComponents/SubscribeViewComponents/SubscribeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CodinaxProjectMvc.ViewComponents.SubscribeViewComponents
{
    public class SubscribeViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Views/Instructors/Index.cshtml
@model InstructorsVm
@inject LanguageService _resource

<main class="main-wrapper">
    <section class="section-hero">
        <div class="padding-global">
            <div class="container-large">
                <div class="padding-section-large" style="padding-bottom: 2rem">
                    <div class="hero-component">
                        <div class="text-align-center padding-section-small">
                            <div data-w-id="d48ee730-c8a5-4405-d9ed-29b2beba958d" class="max-width-large align-center">
                                <div class="padding-bottom padding-xsmall"></div>
                                <h2>
                                    @_resource.GetLocalizedHTML("Begin Your Teaching Journey Today!")
                                </h2>
                                <div class="padding-bottom padding-small"></div>
                                <p>
                                    @_resource.GetLocalizedHTML("Join Our Platform for Seamless Team Collaboration.")
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="shape"></div>
        <div class="shape is-right"></div>
        <div class="shape is-center"></div>
    </section>
    <section class="instructor__area-two">

        <div class="padding-section-small" style="padding-top: 2rem">
            <div class="container" bis_skin_checked="1">


                <div class="instructor__item-wrap-two" bis_skin_checked="1">
                    <div class="row justify-content-center align-center align-items-center" bis_skin_checked="1">
                        <div class="col-xl-8 " bis_skin_checked="1">
                            <div class="instructor__item-two tg-svg" bis_skin_checked="1">
                                <div class="instructor__thumb-two" bis_skin_checked="1">
                                    <img src="https://themegenix.com/demo/skillgro/assets/img/instructor/instructor_two01.png" alt="img">
                                    <div class="shape-one" bis_skin_checked="1">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="224" height="158" viewBox="0 0 224 158" fill="none" data-inject-url="https://themegenix.com/demo/skillgro/assets/img/instructor/instructor_shape01.svg" class="injectable">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M-44.3643 224.756C-12.2393 262.104 53.4544 248.637 109.818 221.047C165.437 193.82 219.176 148.021 222.855 93.9472C226.613 38.7315 180.039 6.40385 124.786 1.08905C73.1398 -3.87887 16.1752 23.3672 -19.5665 70.6284C-58.3852 121.958 -77.2268 186.551 -44.3643 224.756Z" fill="currentcolor"></path>
                                        </svg>
                                    </div>
                                    <div class="shape-two" bis_skin_checked="1">
                                        <span class="svg-icon" id="instructor-svg" data-svg-icon="assets/img/instructor/instructor_shape02.svg">
                                            <svg width="100%" height="100%" viewBox="0 0 48 55" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M42.3863 32.303C40.459 26.5102 36.4329 12.9132 35.7471 4.86755" stroke="#07a169" stroke-width="2" stroke-linejoin="round" style="stroke-dasharray: 29, 31; stroke-dashoffset: 0;"></path>
                                                <path d="M28.5958 42.9917C22.8296 40.9865 9.59837 35.8853 2.80371 31.5222" stroke="#07a169" stroke-width="2" stroke-linejoin="round" style="stroke-dasharray: 29, 31; stroke-dashoffset: 0;"></path>
                                                <path d="M34.3513 34.837C31.2834 32.212 24.4868 25.9248 21.8428 21.7755" stroke="#07a169" stroke-width="2" stroke-linejoin="round" style="stroke-dasharray: 19, 21; stroke-dashoffset: 0;"></path>
                                            </svg>
                                        </span>
                                    </div>
                                </div>
                                <div class="instructor__content-two" bis_skin_checked="1">
                                    <h3 class="title"><a href="/auth/instructor/apply">@_resource.GetLocalizedHTML("Become an Instructor")</a></h3>
                                    <p>@_resource.GetLocalizedHTML("If you're an experienced IT instructor, we invite you to join our team and share your expertise with us.")</p>
                                    <div class="tg-button-wrap" bis_skin_checked="1">
                                        <a href="/auth/instructor/apply" class="btn arrow-btn">
                                            @_resource.GetLocalizedHTML("Apply Now")
                                            <svg width="16" height="14" viewBox="0 0 16 14" fill="none" xmlns="http://www.w3.org/2000/svg" data-inject-url="https://themegenix.com/demo/skillgro/assets/img/icons/right_arrow.svg" class="injectable">
                                                <path d="M1 7L15 7M15 7L9 1M15 7L9 13" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                                                <path d="M1 7L15 7M15 7L9 1M15 7L9 13" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section-team">
        <div class="padding-global">
            <div class="container-large">
                <div class="padding-section-large">
                    <div class="text-align-center" bis_skin_checked="1">
                        <div data-w-id="012fc9d9-3663-3af2-52e1-b9de29d57475" style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="max-width-large align-center" bis_skin_checked="1">
                            <div class="padding-bottom padding-xsmall" bis_skin_checked="1"></div>
                            <h2>
                                @_resource.GetLocalizedHTML("Our Expert") <span class="text-color-primary">@_resource.GetLocalizedHTML("Instructors")</span>
                            </h2>
                            <div class="padding-bottom padding-small" bis_skin_checked="1"></div>
                            <p>
                                @_resource.GetLocalizedHTML("They understand the journey of starting in IT from scratch. Through dedication and effort, they acquired the skills necessary to secure remarkable positions in the industry. Now, they're here to support you in achieving the same success.")
                            </p>
                        </div>
                    </div>

                    <div class="padding-bottom padding-large"></div>
                    <div data-aos="fade-up" data-aos-duration="2000"  class="team-component">

                        <div class="team-list-wrapper w-dyn-list">
                            <div role="list" class="team-list w-dyn-items">
                                @if (Model.Instructors != null && Model.Instructors.Count() > 0)
                                {
                                    @foreach (var instructor in Model.Instructors)
                                    {
                                        <div role="listitem" class="team-item w-dyn-item">
                                            <a href="javascript:void(0);" class="team-card w-inline-block">
                                                <div class="team-top-wrapper">
                                                    <figure class="team-image-wrapper">
                                                        @if (string.IsNullOrEmpty(instructor.ProfileImageName) && string.IsNullOrEmpty(instructor.ProfileImagePathOrContainer))
                                                        {
                                                            <img src="/Assets/panel/assets/img/icon/user.png" loading="lazy" alt="Theresa Webb" class="team-image" />
                                                        }
                                                        else
                                                        {
                                                            <img src="@Model.BaseUrl/@instructor.ProfileImagePathOrContainer/@instructor.ProfileImageName" loading="lazy" alt="Theresa Webb" class="team-image" />
                                                        }

                                                    </figure>
                                                </div>
                                                <div class="team-content">
                                                    <div class="team-text-wrapper">
                                                        <h3 class="heading-style-h6">@instructor.FirstName @instructor.LastName</h3>
                                                        <div>@instructor.Profession</div>
                                                        <p>@instructor.Description</p>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>

                                    }
                                }
                            </div>
                            <div role="navigation" aria-label="List" class="w-pagination-wrapper"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @await Component.InvokeAsync("Faq")

    @await Component.InvokeAsync("Subscribe")
</main>